<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="48" started-at="2019-08-02T04:13:13Z" finished-at="2019-08-02T04:13:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="48" started-at="2019-08-02T04:13:13Z" finished-at="2019-08-02T04:13:13Z">
      <class name="test.day1">
        <test-method status="FAIL" signature="Demo()[pri:0, instance:test.day1@6d78f375]" name="Demo" duration-ms="13" started-at="2019-08-02T00:13:13Z" finished-at="2019-08-02T00:13:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test.day1.Demo(day1.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Demo -->
        <test-method status="PASS" signature="SecondTest()[pri:0, instance:test.day1@6d78f375]" name="SecondTest" duration-ms="3" started-at="2019-08-02T00:13:13Z" finished-at="2019-08-02T00:13:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SecondTest -->
        <test-method status="PASS" signature="lastexecution()[pri:0, instance:test.day1@6d78f375]" name="lastexecution" is-config="true" duration-ms="1" started-at="2019-08-02T00:13:13Z" finished-at="2019-08-02T00:13:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastexecution -->
        <test-method status="PASS" signature="afSyite()[pri:0, instance:test.day1@6d78f375]" name="afSyite" is-config="true" duration-ms="0" started-at="2019-08-02T00:13:13Z" finished-at="2019-08-02T00:13:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afSyite -->
      </class> <!-- test.day1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
